-- =========================================================
-- Atendimento: lideranças / expectativa (planilha Território)
-- Aba: VOTAÇÃO FINAL → public.territorio_liderancas
--
-- Execute no SQL Editor do Supabase ANTES do script de import.
-- =========================================================

CREATE TABLE IF NOT EXISTS public.territorio_liderancas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  municipio TEXT NOT NULL,
  municipio_normalizado TEXT NOT NULL,
  lideranca TEXT NOT NULL,
  senador_1 TEXT,
  senador_2 TEXT,
  dep_estadual TEXT,
  lideranca_atual TEXT,
  cargo_2020 TEXT,
  votos_2020 NUMERIC,
  total_votos_eleicao_2020 NUMERIC,
  cargo_2024 TEXT,
  votos_2024 NUMERIC,
  total_votos_eleicao_2024 NUMERIC,
  promessa_lideranca_2026 NUMERIC,
  total_promessa_lideranca_2026 NUMERIC,
  expectativa_jadyel_2026 NUMERIC,
  total_votos_expectativa_jadyel_2026 NUMERIC,
  votacao_final_2022 NUMERIC,
  expectativa_votos_2026 NUMERIC,
  total_expectativa_votos_2026 NUMERIC,
  diferenca_final_votos_jadyel_2020 NUMERIC,
  pct_acerto_final_votos_jadyel_2020 NUMERIC,
  url_imagem TEXT,
  em_dialogo BOOLEAN NOT NULL DEFAULT FALSE,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  fonte TEXT NOT NULL DEFAULT 'google_sheets',
  imported_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_territorio_liderancas_municipio_norm
  ON public.territorio_liderancas (municipio_normalizado);
CREATE INDEX IF NOT EXISTS idx_territorio_liderancas_municipio
  ON public.territorio_liderancas (municipio);
CREATE INDEX IF NOT EXISTS idx_territorio_liderancas_nome
  ON public.territorio_liderancas (lideranca);
CREATE INDEX IF NOT EXISTS idx_territorio_liderancas_ativo
  ON public.territorio_liderancas (ativo);

ALTER TABLE public.territorio_liderancas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated read territorio_liderancas"
  ON public.territorio_liderancas;
CREATE POLICY "Authenticated read territorio_liderancas"
  ON public.territorio_liderancas
  FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Authenticated insert territorio_liderancas"
  ON public.territorio_liderancas;
CREATE POLICY "Authenticated insert territorio_liderancas"
  ON public.territorio_liderancas
  FOR INSERT TO authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated update territorio_liderancas"
  ON public.territorio_liderancas;
CREATE POLICY "Authenticated update territorio_liderancas"
  ON public.territorio_liderancas
  FOR UPDATE TO authenticated
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated delete territorio_liderancas"
  ON public.territorio_liderancas;
CREATE POLICY "Authenticated delete territorio_liderancas"
  ON public.territorio_liderancas
  FOR DELETE TO authenticated
  USING (true);

COMMENT ON TABLE public.territorio_liderancas IS
  'Lideranças e expectativas por município (planilha Território / VOTAÇÃO FINAL).';
