-- =========================================================
-- Base eleitoral federal 2018 (seção)
-- Execute no SQL Editor do Supabase
-- =========================================================

CREATE TABLE IF NOT EXISTS public.federal_2018 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ano_eleicao INTEGER NOT NULL,
  dt_eleicao DATE,
  cd_municipio INTEGER,
  nm_municipio TEXT,
  nr_zona INTEGER,
  nr_secao INTEGER,
  cd_cargo INTEGER,
  ds_cargo TEXT,
  nr_votavel TEXT,
  nm_votavel TEXT,
  qt_votos INTEGER,
  nr_local_votacao INTEGER,
  sq_candidato BIGINT,
  nm_local_votacao TEXT,
  ds_local_votacao_endereco TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_federal_2018_municipio ON public.federal_2018 (nm_municipio);
CREATE INDEX IF NOT EXISTS idx_federal_2018_votavel_nome ON public.federal_2018 (nm_votavel);
CREATE INDEX IF NOT EXISTS idx_federal_2018_votavel_numero ON public.federal_2018 (nr_votavel);
CREATE INDEX IF NOT EXISTS idx_federal_2018_candidato ON public.federal_2018 (sq_candidato);
CREATE INDEX IF NOT EXISTS idx_federal_2018_zona_secao ON public.federal_2018 (nr_zona, nr_secao);
CREATE INDEX IF NOT EXISTS idx_federal_2018_cargo ON public.federal_2018 (cd_cargo, ds_cargo);
CREATE INDEX IF NOT EXISTS idx_federal_2018_eleicao ON public.federal_2018 (ano_eleicao, dt_eleicao);

ALTER TABLE public.federal_2018 ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated can read federal_2018" ON public.federal_2018;
CREATE POLICY "Authenticated can read federal_2018"
  ON public.federal_2018
  FOR SELECT
  TO authenticated
  USING (true);

-- Escrita recomendada via service role (script de importação).

