import type { CampanhaMaterialPedido } from '@/lib/material-campanha/types'

/** Pedidos fictícios só para pré-visualizar a fila (quando a API ainda está vazia). */
export const MATERIAL_PEDIDOS_MOCK: CampanhaMaterialPedido[] = [
  {
    id: 'mock-pedido-1',
    protocolo: 'MAT-DEMO01',
    status: 'novo',
    solicitante_nome: 'Maria das Dores',
    solicitante_telefone: '8699810-1122',
    municipio: 'Altos',
    destino: 'Comitê municipal — centro',
    observacao: 'Precisa para carreata de sábado de manhã.',
    origem: 'whatsapp',
    whatsapp_message_id: 'wamid.mock.1',
    atendido_por: null,
    atendido_em: null,
    created_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    itens: [
      {
        id: 'mock-item-1a',
        pedido_id: 'mock-pedido-1',
        material_id: 'mock-mat-panf',
        quantidade: 500,
        quantidade_atendida: 0,
        preco_unitario: 0.35,
        material: {
          id: 'mock-mat-panf',
          nome: 'Panfleto institucional',
          codigo: 'PANF-01',
          categoria: 'panfleto',
          unidade: 'un',
          preco_compra: 0.35,
          saldo: 0,
        },
      },
      {
        id: 'mock-item-1b',
        pedido_id: 'mock-pedido-1',
        material_id: 'mock-mat-prag',
        quantidade: 80,
        quantidade_atendida: 0,
        preco_unitario: 2.50,
        material: {
          id: 'mock-mat-prag',
          nome: 'Praguinha de rua',
          codigo: 'PRAG-01',
          categoria: 'praguinha',
          unidade: 'un',
          preco_compra: 2.50,
          saldo: 0,
        },
      },
    ],
    logs: [
      {
        id: 'mock-log-1a',
        pedido_id: 'mock-pedido-1',
        acao: 'criado',
        status_anterior: null,
        status_novo: 'novo',
        user_id: null,
        detalhe: 'Pedido criado via WhatsApp',
        created_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
        usuario: null,
      },
    ],
  },
  {
    id: 'mock-pedido-2',
    protocolo: 'MAT-DEMO02',
    status: 'em_analise',
    solicitante_nome: 'José Carlos Lima',
    solicitante_telefone: '8699200-4455',
    municipio: 'Parnaíba',
    destino: 'TD Planície Litorânea',
    observacao: 'Confirmar se tem adesivo de carro na cor oficial.',
    origem: 'whatsapp',
    whatsapp_message_id: 'wamid.mock.2',
    atendido_por: null,
    atendido_em: null,
    created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    itens: [
      {
        id: 'mock-item-2a',
        pedido_id: 'mock-pedido-2',
        material_id: 'mock-mat-ades',
        quantidade: 120,
        quantidade_atendida: 0,
        preco_unitario: 1.20,
        material: {
          id: 'mock-mat-ades',
          nome: 'Adesivo de carro',
          codigo: 'ADES-01',
          categoria: 'adesivo',
          unidade: 'un',
          preco_compra: 1.20,
          saldo: 0,
        },
      },
      {
        id: 'mock-item-2b',
        pedido_id: 'mock-pedido-2',
        material_id: 'mock-mat-band',
        quantidade: 30,
        quantidade_atendida: 0,
        preco_unitario: 8.00,
        material: {
          id: 'mock-mat-band',
          nome: 'Bandeira de mão',
          codigo: 'BAND-01',
          categoria: 'bandeira',
          unidade: 'un',
          preco_compra: 8.00,
          saldo: 0,
        },
      },
    ],
    logs: [
      {
        id: 'mock-log-2a',
        pedido_id: 'mock-pedido-2',
        acao: 'criado',
        status_anterior: null,
        status_novo: 'novo',
        user_id: null,
        detalhe: 'Pedido criado via WhatsApp',
        created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
        usuario: null,
      },
      {
        id: 'mock-log-2b',
        pedido_id: 'mock-pedido-2',
        acao: 'status_alterado',
        status_anterior: 'novo',
        status_novo: 'em_analise',
        user_id: 'mock-user-ana',
        detalhe: 'novo → em_analise',
        created_at: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
        usuario: { name: 'Ana Coordenação', email: 'ana@campanha.local' },
      },
    ],
  },
  {
    id: 'mock-pedido-3',
    protocolo: 'MAT-DEMO03',
    status: 'aprovado',
    solicitante_nome: 'Ana Paula Sousa',
    solicitante_telefone: '8698811-7788',
    municipio: 'Picos',
    destino: 'Entrega na sede da coligação',
    observacao: null,
    origem: 'manual',
    whatsapp_message_id: null,
    atendido_por: null,
    atendido_em: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    itens: [
      {
        id: 'mock-item-3a',
        pedido_id: 'mock-pedido-3',
        material_id: 'mock-mat-bann',
        quantidade: 4,
        quantidade_atendida: 0,
        preco_unitario: 120.00,
        material: {
          id: 'mock-mat-bann',
          nome: 'Banner 3x1',
          codigo: 'BANN-01',
          categoria: 'banner',
          unidade: 'un',
          preco_compra: 120.00,
          saldo: 0,
        },
      },
      {
        id: 'mock-item-3b',
        pedido_id: 'mock-pedido-3',
        material_id: 'mock-mat-panf',
        quantidade: 1000,
        quantidade_atendida: 0,
        preco_unitario: 0.35,
        material: {
          id: 'mock-mat-panf',
          nome: 'Panfleto institucional',
          codigo: 'PANF-01',
          categoria: 'panfleto',
          unidade: 'un',
          preco_compra: 0.35,
          saldo: 0,
        },
      },
    ],
    logs: [
      {
        id: 'mock-log-3a',
        pedido_id: 'mock-pedido-3',
        acao: 'criado',
        status_anterior: null,
        status_novo: 'novo',
        user_id: 'mock-user-rob',
        detalhe: 'Pedido criado manualmente',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
        usuario: { name: 'Robson', email: 'robson@campanha.local' },
      },
      {
        id: 'mock-log-3b',
        pedido_id: 'mock-pedido-3',
        acao: 'status_alterado',
        status_anterior: 'novo',
        status_novo: 'em_analise',
        user_id: 'mock-user-ana',
        detalhe: 'novo → em_analise',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
        usuario: { name: 'Ana Coordenação', email: 'ana@campanha.local' },
      },
      {
        id: 'mock-log-3c',
        pedido_id: 'mock-pedido-3',
        acao: 'status_alterado',
        status_anterior: 'em_analise',
        status_novo: 'aprovado',
        user_id: 'mock-user-joao',
        detalhe: 'em_analise → aprovado',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
        usuario: { name: 'João Operações', email: 'joao@campanha.local' },
      },
    ],
  },
  {
    id: 'mock-pedido-4',
    protocolo: 'MAT-DEMO04',
    status: 'separado',
    solicitante_nome: 'Raimundo Nunes',
    solicitante_telefone: '8699700-3344',
    municipio: 'Teresina',
    destino: 'Zona Sul — ponto de apoio',
    observacao: 'Já separado na sala de material. Aguardando retirada.',
    origem: 'whatsapp',
    whatsapp_message_id: 'wamid.mock.4',
    atendido_por: null,
    atendido_em: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    itens: [
      {
        id: 'mock-item-4a',
        pedido_id: 'mock-pedido-4',
        material_id: 'mock-mat-camis',
        quantidade: 50,
        quantidade_atendida: 0,
        preco_unitario: 18.00,
        material: {
          id: 'mock-mat-camis',
          nome: 'Camiseta da campanha',
          codigo: 'CAMI-01',
          categoria: 'camiseta',
          unidade: 'un',
          preco_compra: 18.00,
          saldo: 0,
        },
      },
      {
        id: 'mock-item-4b',
        pedido_id: 'mock-pedido-4',
        material_id: 'mock-mat-bone',
        quantidade: 40,
        quantidade_atendida: 0,
        preco_unitario: 15.00,
        material: {
          id: 'mock-mat-bone',
          nome: 'Boné oficial',
          codigo: 'BONE-01',
          categoria: 'bone',
          unidade: 'un',
          preco_compra: 15.00,
          saldo: 0,
        },
      },
      {
        id: 'mock-item-4c',
        pedido_id: 'mock-pedido-4',
        material_id: 'mock-mat-prag',
        quantidade: 25,
        quantidade_atendida: 0,
        preco_unitario: 2.50,
        material: {
          id: 'mock-mat-prag',
          nome: 'Praguinha de rua',
          codigo: 'PRAG-01',
          categoria: 'praguinha',
          unidade: 'un',
          preco_compra: 2.50,
          saldo: 0,
        },
      },
    ],
    logs: [
      {
        id: 'mock-log-4a',
        pedido_id: 'mock-pedido-4',
        acao: 'criado',
        status_anterior: null,
        status_novo: 'novo',
        user_id: null,
        detalhe: 'Pedido criado via WhatsApp',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
        usuario: null,
      },
      {
        id: 'mock-log-4b',
        pedido_id: 'mock-pedido-4',
        acao: 'status_alterado',
        status_anterior: 'novo',
        status_novo: 'em_analise',
        user_id: 'mock-user-ana',
        detalhe: 'novo → em_analise',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
        usuario: { name: 'Ana Coordenação', email: 'ana@campanha.local' },
      },
      {
        id: 'mock-log-4c',
        pedido_id: 'mock-pedido-4',
        acao: 'status_alterado',
        status_anterior: 'em_analise',
        status_novo: 'aprovado',
        user_id: 'mock-user-joao',
        detalhe: 'em_analise → aprovado',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
        usuario: { name: 'João Operações', email: 'joao@campanha.local' },
      },
      {
        id: 'mock-log-4d',
        pedido_id: 'mock-pedido-4',
        acao: 'status_alterado',
        status_anterior: 'aprovado',
        status_novo: 'separado',
        user_id: 'mock-user-lia',
        detalhe: 'aprovado → separado',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
        usuario: { name: 'Lia Almoxarifado', email: 'lia@campanha.local' },
      },
    ],
  },
]

export function isPedidoMockId(id: string): boolean {
  return id.startsWith('mock-pedido-')
}
