/** Rótulos curtos do menu no tema Cockpit Vivo — compartilhado entre sidebar e home kanban. */
export const COCKPIT_MENU_LABEL: Record<string, string> = {
  home: 'Visão',
  'resumo-operacional': 'Resumo',
  'territorio-ipt': 'Mapa Diagnóstico Campanha',
  narrativas: 'Estratégia',
  agenda: 'Agenda',
  territorio: 'Território & Campo',
  'ficha-atendimento': 'Ficha',
  'chapas-menu': 'Chapas',
  'resumo-eleicoes-menu': 'Eleições',
  conteudo: 'Redes Sociais',
  'conteudo-menu': 'Redes Sociais',
  'conteudo-hub': 'Visão',
  'conteudo-obras': 'Obras',
  'conteudo-agenda': 'Agenda',
  'conteudo-cards': 'Cards',
  'conteudo-referencias': 'Referências',
  'conteudo-analise': 'Análise',
  'conteudo-redes': 'Instagram',
  'noticias-menu': 'Central monitor.',
  noticias: 'Monitoramento',
  'mobilizacao-menu': 'Mobilização',
  'mobilizacao-captacao': 'Captação',
  'mobilizacao-config': 'Config',
  whatsapp: 'WhatsApp',
  pesquisa: 'Pesquisas',
  operacao: 'Operação',
  juridico: 'Jurídico',
  obras: 'Obras',
  proposicoes: 'Proposições',
  'sei-pesquisa': 'SEI',
  'gestao-pesquisas-menu': 'Gestão pesq.',
  usuarios: 'Usuários',
  'log-system': 'Log System',
  'jarvis-assistant': 'IA Cockpit',
  chapas: 'Federal',
  'chapas-estaduais': 'Estadual',
  'resumo-eleicoes-principal': 'Por cidade',
  'resumo-eleicoes-historico': 'Hist. federal',
  'resumo-eleicoes-secao': 'Resultados Anteriores',
  'gestao-pesquisas-inicio': 'Início',
  'gestao-pesquisas-config': 'Config',
  emendas: 'Emendas',
}
