/**
 * Catálogo inicial Radar 224 — fase 1 (top 50 + camadas estadual/regional).
 * Fontes locais entram como candidatas nos polos; oficiais ficam em fluxo separado.
 */

import type { RadarFonte } from '@/lib/radar-224/types'

export const RADAR_224_FONTES_SEED: RadarFonte[] = [
  // ——— Estaduais (cobertura-base 224) ———
  {
    id: 'gp1',
    nome: 'GP1',
    camada: 'estadual',
    selo: 'Imprensa estadual',
    url: 'https://www.gp1.com.br/pi/piaui/',
    dominio: 'gp1.com.br',
    nota: 92,
    status: 'ativa',
    territorios: [],
    municipiosPrioritarios: [],
    coberturaResumo: 'Índice de municípios do Piauí com páginas por cidade',
    notasOperacionais: 'Priorizar URLs /pi/… e páginas municipais do índice',
  },
  {
    id: 'meionews',
    nome: 'MeioNews',
    camada: 'estadual',
    selo: 'Imprensa estadual',
    url: 'https://www.meionews.com/cidades-meio',
    dominio: 'meionews.com',
    nota: 90,
    status: 'ativa',
    territorios: [],
    municipiosPrioritarios: [],
    coberturaResumo: 'Área Cidades Meio com seleção por município',
  },
  {
    id: '180graus',
    nome: '180graus',
    camada: 'estadual',
    selo: 'Imprensa estadual',
    url: 'https://180graus.com/',
    dominio: '180graus.com',
    nota: 90,
    status: 'ativa',
    territorios: [],
    municipiosPrioritarios: [],
    coberturaResumo: 'Portal estadual com páginas próprias por município',
  },

  // ——— Regionais por TD ———
  {
    id: 'riachaonet',
    nome: 'RiachãoNet',
    camada: 'regional',
    selo: 'Imprensa regional',
    url: 'https://www.riachaonet.com.br/portal/',
    dominio: 'riachaonet.com.br',
    nota: 88,
    status: 'ativa',
    territorios: ['Vale do Rio Guaribas', 'Chapada do Vale do Rio Itaim'],
    municipiosPrioritarios: ['PICOS', 'PIO IX', 'DOM EXPEDITO LOPES', 'SANTANA DO PIAUÍ', 'JAICÓS', 'MARCOLÂNDIA'],
    coberturaResumo: 'Picos e Centro-Sul (~44 cidades da macrorregião)',
  },
  {
    id: 'grande-picos',
    nome: 'Portal Grande Picos',
    camada: 'regional',
    selo: 'Imprensa regional',
    url: 'https://grandepicos.com.br/',
    dominio: 'grandepicos.com.br',
    nota: 82,
    status: 'ativa',
    territorios: ['Vale do Rio Guaribas'],
    municipiosPrioritarios: ['PICOS', 'PIO IX', 'DOM EXPEDITO LOPES'],
    coberturaResumo: 'Polo Picos e entorno',
  },
  {
    id: 'picos-40-graus',
    nome: 'Picos 40 Graus',
    camada: 'regional',
    selo: 'Imprensa regional',
    url: 'https://picos40graus.com.br/',
    dominio: 'picos40graus.com.br',
    nota: 75,
    status: 'candidata',
    territorios: ['Vale do Rio Guaribas'],
    municipiosPrioritarios: ['PICOS'],
    coberturaResumo: 'Complementar Picos / Centro-Sul — validar frequência',
  },
  {
    id: 'portal-costa-norte',
    nome: 'Portal Costa Norte',
    camada: 'regional',
    selo: 'Imprensa regional',
    url: 'https://portalcostanorte.com.br/',
    dominio: 'portalcostanorte.com.br',
    nota: 84,
    status: 'ativa',
    territorios: ['Planície Litorânea'],
    municipiosPrioritarios: ['PARNAÍBA', 'LUIS CORREIA', 'COCAL', 'ILHA GRANDE', 'CAJUEIRO DA PRAIA', 'BURITI DOS LOPES'],
    coberturaResumo: 'Parnaíba e litoral',
  },
  {
    id: 'plantao-parnaiba',
    nome: 'Plantão Parnaíba',
    camada: 'regional',
    selo: 'Imprensa regional',
    url: 'https://www.plantaoparnaiba.com.br/',
    dominio: 'plantaoparnaiba.com.br',
    nota: 78,
    status: 'candidata',
    territorios: ['Planície Litorânea'],
    municipiosPrioritarios: ['PARNAÍBA', 'LUIS CORREIA'],
    coberturaResumo: 'Polo Parnaíba — validar RSS/atualização',
  },
  {
    id: 'jornal-da-parnaiba',
    nome: 'Jornal da Parnaíba',
    camada: 'regional',
    selo: 'Imprensa regional',
    url: 'https://www.jornaldaparnaiba.com/',
    dominio: 'jornaldaparnaiba.com',
    nota: 76,
    status: 'candidata',
    territorios: ['Planície Litorânea'],
    municipiosPrioritarios: ['PARNAÍBA'],
    coberturaResumo: 'Imprensa local/regional do litoral',
  },
  {
    id: 'campo-maior-em-foco',
    nome: 'Campo Maior em Foco',
    camada: 'regional',
    selo: 'Imprensa regional',
    url: 'https://www.campomaioremfoco.com.br/',
    dominio: 'campomaioremfoco.com.br',
    nota: 80,
    status: 'ativa',
    territorios: ['Carnaubais'],
    municipiosPrioritarios: ['CAMPO MAIOR', 'CAPITÃO DE CAMPOS', 'SIGEFREDO PACHECO'],
    coberturaResumo: 'Campo Maior e Carnaubais',
  },
  {
    id: 'diario-campo-maior',
    nome: 'Diário de Campo Maior',
    camada: 'regional',
    selo: 'Imprensa regional',
    url: 'https://www.diariodecampomaior.com.br/',
    dominio: 'diariodecampomaior.com.br',
    nota: 74,
    status: 'candidata',
    territorios: ['Carnaubais'],
    municipiosPrioritarios: ['CAMPO MAIOR'],
    coberturaResumo: 'Complementar Campo Maior',
  },
  {
    id: 'piaui-noticias',
    nome: 'Piauí Notícias',
    camada: 'regional',
    selo: 'Imprensa regional',
    url: 'https://www.piauinoticias.com/',
    dominio: 'piauinoticias.com',
    nota: 80,
    status: 'ativa',
    territorios: ['Vale dos Rios Piauí e Itaueira', 'Vale do Canindé'],
    municipiosPrioritarios: ['CANTO DO BURITI', 'ITAUEIRA', 'OEIRAS', 'PAES LANDIM'],
    coberturaResumo: 'Floriano / Médio Parnaíba e eixo sul-central',
  },
  {
    id: 'floriano-news',
    nome: 'Floriano News',
    camada: 'regional',
    selo: 'Imprensa regional',
    url: 'https://www.florianonews.com/',
    dominio: 'florianonews.com',
    nota: 72,
    status: 'candidata',
    territorios: ['Vale dos Rios Piauí e Itaueira'],
    municipiosPrioritarios: ['CANTO DO BURITI', 'ITAUEIRA'],
    coberturaResumo: 'Floriano e entorno — validar cobertura no top 50',
  },
  {
    id: 'portal-b1',
    nome: 'Portal B1',
    camada: 'regional',
    selo: 'Imprensa regional',
    url: 'https://www.portalb1.com.br/',
    dominio: 'portalb1.com.br',
    nota: 78,
    status: 'ativa',
    territorios: ['Chapada das Mangabeiras', 'Tabuleiros do Alto Parnaíba'],
    municipiosPrioritarios: ['CORRENTE', 'PARNAGUÁ'],
    coberturaResumo: 'Bom Jesus / extremo Sul',
  },

  // ——— Locais (candidatos nos polos do top 50) ———
  {
    id: 'local-teresina-cidadeverde',
    nome: 'Cidade Verde (Teresina)',
    camada: 'local',
    selo: 'Portal local',
    url: 'https://cidadeverde.com/',
    dominio: 'cidadeverde.com',
    nota: 85,
    status: 'candidata',
    territorios: ['Entre Rios'],
    municipiosPrioritarios: ['TERESINA', 'ALTOS', 'DEMERVAL LOBÃO', 'UNIÃO'],
    coberturaResumo: 'Polo Teresina / Grande Teresina',
    notasOperacionais: 'Validar se trata como local ou quase estadual',
  },
  {
    id: 'local-pedro-ii',
    nome: 'Portal local Pedro II (a definir)',
    camada: 'local',
    selo: 'Portal local',
    url: '',
    dominio: '',
    nota: 40,
    status: 'candidata',
    territorios: ['Cocais'],
    municipiosPrioritarios: ['PEDRO II', 'PIRACURUCA'],
    coberturaResumo: 'Slot para fonte local Cocais após auditoria de 30 dias',
  },
  {
    id: 'local-cocal',
    nome: 'Portal local Cocal (a definir)',
    camada: 'local',
    selo: 'Portal local',
    url: '',
    dominio: '',
    nota: 35,
    status: 'candidata',
    territorios: ['Planície Litorânea'],
    municipiosPrioritarios: ['COCAL'],
    coberturaResumo: 'Alta expectativa · baixa cobertura local cadastrada',
  },

  // ——— Oficiais (fluxo separado) ———
  {
    id: 'oficial-governo-pi',
    nome: 'Governo do Estado do Piauí',
    camada: 'oficial',
    selo: 'Fonte oficial',
    url: 'https://www.pi.gov.br/',
    dominio: 'pi.gov.br',
    nota: 70,
    status: 'ativa',
    territorios: [],
    municipiosPrioritarios: [],
    coberturaResumo: 'Releases estaduais — nunca misturar com imprensa',
  },
  {
    id: 'oficial-tce-pi',
    nome: 'TCE-PI',
    camada: 'oficial',
    selo: 'Fonte oficial',
    url: 'https://www.tce.pi.gov.br/',
    dominio: 'tce.pi.gov.br',
    nota: 75,
    status: 'ativa',
    territorios: [],
    municipiosPrioritarios: [],
    coberturaResumo: 'Controle externo — alertas de risco/reputação',
  },
  {
    id: 'oficial-mppi',
    nome: 'MPPI',
    camada: 'oficial',
    selo: 'Fonte oficial',
    url: 'https://www.mppi.mp.br/',
    dominio: 'mppi.mp.br',
    nota: 75,
    status: 'ativa',
    territorios: [],
    municipiosPrioritarios: [],
    coberturaResumo: 'Ministério Público — denúncias e ações',
  },
  {
    id: 'oficial-ssp-pi',
    nome: 'SSP-PI',
    camada: 'oficial',
    selo: 'Fonte oficial',
    url: 'https://www.ssp.pi.gov.br/',
    dominio: 'ssp.pi.gov.br',
    nota: 72,
    status: 'ativa',
    territorios: [],
    municipiosPrioritarios: [],
    coberturaResumo: 'Segurança pública estadual',
  },
]

export function listRadarFontesSeed(opts?: {
  camada?: RadarFonte['camada']
  status?: RadarFonte['status'] | RadarFonte['status'][]
}): RadarFonte[] {
  let list = [...RADAR_224_FONTES_SEED]
  if (opts?.camada) list = list.filter((f) => f.camada === opts.camada)
  if (opts?.status) {
    const set = new Set(Array.isArray(opts.status) ? opts.status : [opts.status])
    list = list.filter((f) => set.has(f.status))
  }
  return list.sort((a, b) => b.nota - a.nota || a.nome.localeCompare(b.nome, 'pt-BR'))
}
